
ENV['AWS_BUCKET']='mxmny'
ENV['AWS_ACCESS_KEY_ID'] = "AKIAIXJB7QC2V22PN5UQ"
ENV['AWS_SECRET_ACCESS_KEY'] = "kmk2k8GvMTdM78kHbrPPf79RPQejphyiLUHBINNy/hzdEuQFjf4gA6IycOR+bOY"


ENV['PUBLISHABLE_KEY']='pk_test_85dgBVCarVWNxR6rCOEovf2p'
ENV['SECRET_KEY']='sk_test_CtY58gVmXdha8d24wKMoRZCI'

