
ENV['AWS_BUCKET']='mxmny'
ENV['AWS_ACCESS_KEY_ID'] = "AKIAJDDAE4ND4LGMSCFA"
ENV['AWS_SECRET_ACCESS_KEY'] = "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"


ENV['PUBLISHABLE_KEY']='pk_test_85dgBVCarVWNxR6rCOEovf2p'
ENV['SECRET_KEY']='sk_test_CtY58gVmXdha8d24wKMoRZCI'

