ENV['PUBLISHABLE_KEY']='pk_test_85dgBVCarVWNxR6rCOEovf2p'
ENV['SECRET_KEY']='sk_test_CtY58gVmXdha8d24wKMoRZCI'


ENV['AZBUCKET']='azstore'
ENV['AZ_ACCESS_KEY_ID'] = "AKIAJ2ZJGVBFWKL34UDA"
ENV['AZ_SECRET_ACCESS_KEY'] = "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"